name: Deploy para Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Enviar via FTP para Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server:   ${{ secrets.FTPHOST }}
          username: ${{ secrets.FTPUSER }}
          password: ${{ secrets.FTPPASSW }}
          local-dir: ./
          server-dir: /public_html/
          exclude: |
            **/.git*
            **/.git*/**
            **/CLAUDE.md
            **/SKILLS/**
            **/SIM-primitivos-design-system.md
            **/specs-apple-design.md
            **/Texto-site.txt
            **/*.md
